### ISSUE TITLE
Package

### ISSUE THREAD

**Issue by m3m0ry** [berni44/printFloat#1]
I am trying to print strings at compile time, for a string mixin.
I have found [this](https://github.com/night-shift/fpconv), but it is not a package and your work seems to be more solid and tested. (it works though)

Could you make a package and submit it to code.dlang.org, so I can use it?
First of all, I am sure, other would want that as well, since the float to string implementation in phobos does not support CTFE.
I would do it myself, but i have no idea how this thing works. (I am new to D and although I have made a simple [package](https://code.dlang.org/packages/fixedpoint) myself, i am still not completely sure, how the modules work.

**Comment by berni44** [comment]
> Could you make a package and submit it to code.dlang.org, so I can use it?
> First of all, I am sure, other would want that as well, since the float to string implementation in phobos does not support CTFE.

Actually the sole purpose of these functions is to replace the function in Phobos (which currently relies on the `snprintf` function from C and therefore cannot be CTFE.)

In the nightly build of Phobos the versions for `%a` and `%e` are allready included and I hope for `%f` to follow soon (see [PR](https://github.com/dlang/phobos/pull/7264) After that I can go for `%g` which depends on `%e` and `%f`. And then the next goal is CTFE. Please note, that this works only for `float` and `double`. `real` is not implemented yet.

**Comment by m3m0ry** [comment]
Ah, that is great!

So i will just wait, until it gets merged. I can imagine it takes some time, since printing of floating point numbers is extremely hard. I have never done it myself, and I hope I will never need to.

Thank you for the effort!

Meanwhile i will use the previously mentioned solution.
